# Generated by Django 4.2.3 on 2023-07-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(max_length=250)),
                ('Pimg', models.ImageField(upload_to='per')),
                ('Pdesc', models.TextField()),
            ],
        ),
    ]
